#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define SCREEN_WIDTH 1500
#define SCREEN_HEIGHT 1250

#define FRAME_LIMIT 60

#define NUMBER_ROWS 25
#define NUMBER_COLUMNS 15
#define CELL_SIZE 50

#define TIME_DOWN 0.5

#define CHARACTER_SIZE 35
#define CHARACTER_SCORE_SIZE 45
#define CHARACTER_UPDATE_SIZE 80

#define WIDTH_SCORE 900
#define HEIGHT_SCORE 70

#define WIDTH_UPDATE_SCORE 1220
#define HEIGHT_UPDATE_SCORE 5

#define WIDTH_NEXT 930
#define HEIGHT_NEXT 500

#define WIDTH_GAMEOVER 930
#define HEIGHT_GAMEOVER 900

#define DELTA_TIME 0.2

#endif