#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define SCREEN_WIDTH 1800
#define SCREEN_HEIGHT 1600

#define FRAME_LIMIT 60

#define NUMBER_ROWS 25
#define NUMBER_COLUMNS 15
#define CELL_SIZE 50

#define TIME_DOWN 0.5

#define PADDING 30
#define OFFSET 1

#define CHARACTER_SIZE 35
#define CHARACTER_SCORE_SIZE 45
#define CHARACTER_UPDATE_SIZE 60
#define CHARACTER_CONTROL_SIZE 20

#define WIDTH_SCORE 900
#define HEIGHT_SCORE 70

#define WIDTH_LEVEL 1470
#define HEIGHT_LEVEL 70

#define WIDTH_UPDATE_LEVEL 1550
#define HEIGHT_UPDATE_LEVEL 170

#define WIDTH_UPDATE_SCORE 1220
#define HEIGHT_UPDATE_SCORE 40

#define WIDTH_NEXT 930
#define HEIGHT_NEXT 500

#define WIDTH_RECT 900
#define HEIGHT_RECT 600

#define X_MEDAL 1000
#define Y_MEDAL 170

#define WIDTH_NEXT_BLOCK 880
#define HEIGHT_NEXT_BLOCK 650

#define WIDTH_RECT_SIZE 400
#define HEIGHT_RECT_SIZE 200

#define RECT_THICKNESS 4

#define WIDTH_GAMEOVER 910
#define HEIGHT_GAMEOVER 950

#define CHARACTER_GAMEOVER_SIZE 45
#define CHARACTER_PLAY_AGAIN_SIZE 25

#define WIDTH_TIME 860
#define HEIGHT_TIME 1350

#define WIDTH_CONTROL 80
#define HEIGHT_CONTROL 1300

#define WIDTH_PLAY_AGAIN 860
#define HEIGHT_PLAY_AGAIN 1100

#define MUSIC_VOLUME 50
#define SOUND_VOLUME 70

#endif