#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define SCREEN_WIDTH 1500
#define SCREEN_HEIGHT 1250

#define FRAME_LIMIT 60

#define NUMBER_ROWS 25
#define NUMBER_COLUMNS 15
#define CELL_SIZE 50

#define TIME_DOWN 0.5

#define CHARACTER_SIZE 64

#define WIDTH_SCORE 1000
#define HEIGHT_SCORE 15

#define WIDTH_NEXT 900
#define HEIGHT_NEXT 500

#define WIDTH_GAMEOVER 900
#define HEIGHT_GAMEOVER 900

#endif